
/* START 손보연*/
INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
VALUES (CATEGORY_SEQ.NEXTVAL, 'category.bed', NULL, 1, 'Y');
/* 이게 큰 카테고리 */

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.bed', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.bed';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.mattress', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.bed';
/* 이게 작은 카테고리 */

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.bedding', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.bed';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.bedsideTable', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.bed';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.headboard', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.bed';
/* END 손보연*/


/* START 박성섭*/
INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
VALUES (CATEGORY_SEQ.NEXTVAL, 'category.diningTablesChairs', NULL, 1, 'Y');
/* 이게 큰 카테고리 */

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.diningFurniture', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.diningTablesChairs';
/* 이게 작은 카테고리 */

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.table', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.diningTablesChairs';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.chair', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.diningTablesChairs';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.coffeeTable', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.diningTablesChairs';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.barTableChair', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.diningTablesChairs';
/* END 박성섭*/


/* START 김연준*/
INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
VALUES (CATEGORY_SEQ.NEXTVAL, 'category.kids', NULL, 1, 'Y');
/* 이게 큰 카테고리 */

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.bedTent', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kids';
/* 이게 작은 카테고리 */

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.clock', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kids';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.chestOfDrawers', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kids';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.clothesRack', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kids';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.playKitchenSet', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kids';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.stool', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kids';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.tableChairSet', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kids';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.compartmentOrganizer', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kids';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.storageCombination', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kids';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.organizingCart', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kids';
/* END 김연준*/


/* nav.* 는 이미 국제화 키라 그대로 둠 */
INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
VALUES (CATEGORY_SEQ.NEXTVAL, 'nav.livingroom', NULL, 1, 'Y');

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'nav.chair', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'nav.livingroom';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'nav.sofa', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'nav.livingroom';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'nav.closet', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'nav.livingroom';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'nav.table', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'nav.livingroom';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'nav.lighting', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'nav.livingroom';


/* START 손보연 */
INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
VALUES (CATEGORY_SEQ.NEXTVAL, 'category.kitchen', NULL, 1, 'Y');
/* 이게 큰 카테고리 */

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.table-texti', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kitchen';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.plates_bowls', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kitchen';
/* 이게 작은 카테고리 */

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.pots_pans', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kitchen';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.glassware_bottles', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kitchen';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.kids_tableware', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.kitchen';
/* END 손보연 */




/* START 장재혁*/
INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
VALUES (CATEGORY_SEQ.NEXTVAL, 'category.sofa', NULL, 1, 'Y');
/* 이게 큰 카테고리 */

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.sofa', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.sofa';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.armchairRecliner', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.sofa';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.sofaBed', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.sofa';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.sofaLegs', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.sofa';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.footstool', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.sofa';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.chaiseLounge', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.sofa';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.sofaCover', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.sofa';

INSERT INTO CATEGORY (CATEGORY_ID, NAME_KEY, PARENT_ID, SORT_ORDER, USE_YN)
SELECT CATEGORY_SEQ.NEXTVAL, 'category.sofaCushion', p.CATEGORY_ID, 1, 'Y'
FROM CATEGORY p
WHERE p.NAME_KEY = 'category.sofa';
/* END 장재혁*/
